name: Build and Release Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0
          
      - name: Download the MSP library from Polybox (Linux/macOS)
        run: |
        curl -L -o MoNA-export-All_LC-MS-MS_Orbitrap.zip "https://polybox.ethz.ch/index.php/s/CrnWdgwX5canNxL/download"
        unzip -o MoNA-export-All_LC-MS-MS_Orbitrap.zip
        ls -la
        mv MoNA-export-All_LC-MS-MS_Orbitrap.msp lc-inspector/resources
        shell: bash
        if: matrix.os != 'windows-latest'

      - name: Download the MSP library from Polybox (Windows)
        run: |
        Invoke-WebRequest -Uri "https://polybox.ethz.ch/index.php/s/CrnWdgwX5canNxL/download" -OutFile "MoNA-export-All_LC-MS-MS_Orbitrap.zip"
        Expand-Archive -Path MoNA-export-All_LC-MS-MS_Orbitrap.zip -DestinationPath "." -Force
        Get-ChildItem
        Move-Item -Path "MoNA-export-All_LC-MS-MS_Orbitrap.msp" -Destination "lc-inspector/resources"
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build executable (macOS)
        run: |
         cd lc-inspector/
         pyinstaller --name "LCMSpector" --icon icon.icns --exclude-module torch --exclude-module matplotlib --exclude-module frozendict --exclude-module torchvision --exclude-module torchgen --exclude-module tqdm --exclude-module torchaudio --add-data "ui/logo.png:ui" --add-data "config.json:." --add-data "app.log:." --add-data "resources/MoNA-export-All_LC-MS-MS_Orbitrap.msp:resources" --onedir --windowed main.py
        shell: bash
        if: matrix.os == 'macos-latest'

      - name: Build executable (Windows)
        run:  |
         cd lc-inspector/
         pip install pillow
         pyinstaller --name "LCMSpector" --icon icon.icns --exclude-module torch --exclude-module matplotlib --exclude-module frozendict --exclude-module torchvision --exclude-module torchgen --exclude-module tqdm --exclude-module torchaudio --add-data "ui/logo.png:ui" --add-data "config.json:." --add-data "app.log:." --add-data "resources/MoNA-export-All_LC-MS-MS_Orbitrap.msp:resources" --noconsole --onedir main.py
        shell: cmd
        if: matrix.os == 'windows-latest'

      - name: Zip artifact for deployment (Windows)
        run: tar.exe -acvf LCMSpector-${{ github.event.inputs.version }}-Win11-x86_64.zip lc-inspector/dist/LCMSpector
        shell: cmd
        if: matrix.os == 'windows-latest'

      - name: Zip artifact for deployment (macOS)
        run: zip -r LCMSpector-${{ github.event.inputs.version }}-macOS-arm64.zip lc-inspector/dist/LCMSpector.app
        shell: bash
        if: matrix.os == 'macos-latest'

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: lcmspector-${{ github.event.inputs.version }}-macOS-arm64.zip
          path: ./*.zip
        if: matrix.os == 'macos-latest'
        
      - name: Upload arifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: lcmspector-${{ github.event.inputs.version }}-Win11-x86_64.zip
          path: ./*.zip
        if: matrix.os == 'windows-latest'

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            lcmspector-${{ github.event.inputs.version }}-macOS-arm64.zip
            lcmspector-${{ github.event.inputs.version }}-Win11-x86_64.zip

